INSERT INTO country (name, code) values ('Afghanistan', 'AFG');
INSERT INTO country (name, code) values ('Albania', 'ALB');
INSERT INTO country (name, code) values ('Algeria', 'DZA');
INSERT INTO country (name, code) values ('American Samoa', 'ASM');
INSERT INTO country (name, code) values ('Andorra', 'AND');
INSERT INTO country (name, code) values ('Angola', 'AGO');
INSERT INTO country (name, code) values ('Anguilla', 'AIA');
INSERT INTO country (name, code) values ('Antarctica', 'ATA');
INSERT INTO country (name, code) values ('Antigua and Barbuda', 'ATG');
INSERT INTO country (name, code) values ('Argentina', 'ARG');
INSERT INTO country (name, code) values ('Armenia', 'ARM');
INSERT INTO country (name, code) values ('Aruba', 'ABW');
INSERT INTO country (name, code) values ('Australia', 'AUS');
INSERT INTO country (name, code) values ('Austria', 'AUT');
INSERT INTO country (name, code) values ('Azerbaijan', 'AZE');
INSERT INTO country (name, code) values ('Bahamas (the)', 'BHS');
INSERT INTO country (name, code) values ('Bahrain', 'BHR');
INSERT INTO country (name, code) values ('Bangladesh', 'BGD');
INSERT INTO country (name, code) values ('Barbados', 'BRB');
INSERT INTO country (name, code) values ('Belarus', 'BLR');
INSERT INTO country (name, code) values ('Belgium', 'BEL');
INSERT INTO country (name, code) values ('Belize', 'BLZ');
INSERT INTO country (name, code) values ('Benin', 'BEN');
INSERT INTO country (name, code) values ('Bermuda', 'BMU');
INSERT INTO country (name, code) values ('Bhutan', 'BTN');
INSERT INTO country (name, code) values ('Bolivia (Plurinational State of)', 'BOL');
INSERT INTO country (name, code) values ('Bonaire, Sint Eustatius and Saba', 'BES');
INSERT INTO country (name, code) values ('Bosnia and Herzegovina', 'BIH');
INSERT INTO country (name, code) values ('Botswana', 'BWA');
INSERT INTO country (name, code) values ('Bouvet Island', 'BVT');
INSERT INTO country (name, code) values ('Brazil', 'BRA');
INSERT INTO country (name, code) values ('British Indian Ocean Territory (the)', 'IOT');
INSERT INTO country (name, code) values ('Brunei Darussalam', 'BRN');
INSERT INTO country (name, code) values ('Bulgaria', 'BGR');
INSERT INTO country (name, code) values ('Burkina Faso', 'BFA');
INSERT INTO country (name, code) values ('Burundi', 'BDI');
INSERT INTO country (name, code) values ('Cabo Verde', 'CPV');
INSERT INTO country (name, code) values ('Cambodia', 'KHM');
INSERT INTO country (name, code) values ('Cameroon', 'CMR');
INSERT INTO country (name, code) values ('Canada', 'CAN');
INSERT INTO country (name, code) values ('Cayman Islands (the)', 'CYM');
INSERT INTO country (name, code) values ('Central African Republic (the)', 'CAF');
INSERT INTO country (name, code) values ('Chad', 'TCD');
INSERT INTO country (name, code) values ('Chile', 'CHL');
INSERT INTO country (name, code) values ('China', 'CHN');
INSERT INTO country (name, code) values ('Christmas Island', 'CXR');
INSERT INTO country (name, code) values ('Cocos (Keeling) Islands (the)', 'CCK');
INSERT INTO country (name, code) values ('Colombia', 'COL');
INSERT INTO country (name, code) values ('Comoros (the)', 'COM');
INSERT INTO country (name, code) values ('Congo (the Democratic Republic of the)', 'COD');
INSERT INTO country (name, code) values ('Congo (the)', 'COG');
INSERT INTO country (name, code) values ('Cook Islands (the)', 'COK');
INSERT INTO country (name, code) values ('Costa Rica', 'CRI');
INSERT INTO country (name, code) values ('Croatia', 'HRV');
INSERT INTO country (name, code) values ('Cuba', 'CUB');
INSERT INTO country (name, code) values ('Curaçao', 'CUW');
INSERT INTO country (name, code) values ('Cyprus', 'CYP');
INSERT INTO country (name, code) values ('Czechia', 'CZE');
INSERT INTO country (name, code) values ('Côte d''Ivoire', 'CIV');
INSERT INTO country (name, code) values ('Denmark', 'DNK');
INSERT INTO country (name, code) values ('Djibouti', 'DJI');
INSERT INTO country (name, code) values ('Dominica', 'DMA');
INSERT INTO country (name, code) values ('Dominican Republic (the)', 'DOM');
INSERT INTO country (name, code) values ('Ecuador', 'ECU');
INSERT INTO country (name, code) values ('Egypt', 'EGY');
INSERT INTO country (name, code) values ('El Salvador', 'SLV');
INSERT INTO country (name, code) values ('Equatorial Guinea', 'GNQ');
INSERT INTO country (name, code) values ('Eritrea', 'ERI');
INSERT INTO country (name, code) values ('Estonia', 'EST');
INSERT INTO country (name, code) values ('Eswatini', 'SWZ');
INSERT INTO country (name, code) values ('Ethiopia', 'ETH');
INSERT INTO country (name, code) values ('Falkland Islands (the) [Malvinas]', 'FLK');
INSERT INTO country (name, code) values ('Faroe Islands (the)', 'FRO');
INSERT INTO country (name, code) values ('Fiji', 'FJI');
INSERT INTO country (name, code) values ('Finland', 'FIN');
INSERT INTO country (name, code) values ('France', 'FRA');
INSERT INTO country (name, code) values ('French Guiana', 'GUF');
INSERT INTO country (name, code) values ('French Polynesia', 'PYF');
INSERT INTO country (name, code) values ('French Southern Territories (the)', 'ATF');
INSERT INTO country (name, code) values ('Gabon', 'GAB');
INSERT INTO country (name, code) values ('Gambia (the)', 'GMB');
INSERT INTO country (name, code) values ('Georgia', 'GEO');
INSERT INTO country (name, code) values ('Germany', 'DEU');
INSERT INTO country (name, code) values ('Ghana', 'GHA');
INSERT INTO country (name, code) values ('Gibraltar', 'GIB');
INSERT INTO country (name, code) values ('Greece', 'GRC');
INSERT INTO country (name, code) values ('Greenland', 'GRL');
INSERT INTO country (name, code) values ('Grenada', 'GRD');
INSERT INTO country (name, code) values ('Guadeloupe', 'GLP');
INSERT INTO country (name, code) values ('Guam', 'GUM');
INSERT INTO country (name, code) values ('Guatemala', 'GTM');
INSERT INTO country (name, code) values ('Guernsey', 'GGY');
INSERT INTO country (name, code) values ('Guinea', 'GIN');
INSERT INTO country (name, code) values ('Guinea-Bissau', 'GNB');
INSERT INTO country (name, code) values ('Guyana', 'GUY');
INSERT INTO country (name, code) values ('Haiti', 'HTI');
INSERT INTO country (name, code) values ('Heard Island and McDonald Islands', 'HMD');
INSERT INTO country (name, code) values ('Holy See (the)', 'VAT');
INSERT INTO country (name, code) values ('Honduras', 'HND');
INSERT INTO country (name, code) values ('Hong Kong', 'HKG');
INSERT INTO country (name, code) values ('Hungary', 'HUN');
INSERT INTO country (name, code) values ('Iceland', 'ISL');
INSERT INTO country (name, code) values ('India', 'IND');
INSERT INTO country (name, code) values ('Indonesia', 'IDN');
INSERT INTO country (name, code) values ('Iran (Islamic Republic of)', 'IRN');
INSERT INTO country (name, code) values ('Iraq', 'IRQ');
INSERT INTO country (name, code) values ('Ireland', 'IRL');
INSERT INTO country (name, code) values ('Isle of Man', 'IMN');
INSERT INTO country (name, code) values ('Israel', 'ISR');
INSERT INTO country (name, code) values ('Italy', 'ITA');
INSERT INTO country (name, code) values ('Jamaica', 'JAM');
INSERT INTO country (name, code) values ('Japan', 'JPN');
INSERT INTO country (name, code) values ('Jersey', 'JEY');
INSERT INTO country (name, code) values ('Jordan', 'JOR');
INSERT INTO country (name, code) values ('Kazakhstan', 'KAZ');
INSERT INTO country (name, code) values ('Kenya', 'KEN');
INSERT INTO country (name, code) values ('Kiribati', 'KIR');
INSERT INTO country (name, code) values ('Korea (the Democratic People''s Republic of)', 'PRK');
INSERT INTO country (name, code) values ('Korea (the Republic of)', 'KOR');
INSERT INTO country (name, code) values ('Kuwait', 'KWT');
INSERT INTO country (name, code) values ('Kyrgyzstan', 'KGZ');
INSERT INTO country (name, code) values ('Lao People''s Democratic Republic (the)', 'LAO');
INSERT INTO country (name, code) values ('Latvia', 'LVA');
INSERT INTO country (name, code) values ('Lebanon', 'LBN');
INSERT INTO country (name, code) values ('Lesotho', 'LSO');
INSERT INTO country (name, code) values ('Liberia', 'LBR');
INSERT INTO country (name, code) values ('Libya', 'LBY');
INSERT INTO country (name, code) values ('Liechtenstein', 'LIE');
INSERT INTO country (name, code) values ('Lithuania', 'LTU');
INSERT INTO country (name, code) values ('Luxembourg', 'LUX');
INSERT INTO country (name, code) values ('Macao', 'MAC');
INSERT INTO country (name, code) values ('Madagascar', 'MDG');
INSERT INTO country (name, code) values ('Malawi', 'MWI');
INSERT INTO country (name, code) values ('Malaysia', 'MYS');
INSERT INTO country (name, code) values ('Maldives', 'MDV');
INSERT INTO country (name, code) values ('Mali', 'MLI');
INSERT INTO country (name, code) values ('Malta', 'MLT');
INSERT INTO country (name, code) values ('Marshall Islands (the)', 'MHL');
INSERT INTO country (name, code) values ('Martinique', 'MTQ');
INSERT INTO country (name, code) values ('Mauritania', 'MRT');
INSERT INTO country (name, code) values ('Mauritius', 'MUS');
INSERT INTO country (name, code) values ('Mayotte', 'MYT');
INSERT INTO country (name, code) values ('Mexico', 'MEX');
INSERT INTO country (name, code) values ('Micronesia (Federated States of)', 'FSM');
INSERT INTO country (name, code) values ('Moldova (the Republic of)', 'MDA');
INSERT INTO country (name, code) values ('Monaco', 'MCO');
INSERT INTO country (name, code) values ('Mongolia', 'MNG');
INSERT INTO country (name, code) values ('Montenegro', 'MNE');
INSERT INTO country (name, code) values ('Montserrat', 'MSR');
INSERT INTO country (name, code) values ('Morocco', 'MAR');
INSERT INTO country (name, code) values ('Mozambique', 'MOZ');
INSERT INTO country (name, code) values ('Myanmar', 'MMR');
INSERT INTO country (name, code) values ('Namibia', 'NAM');
INSERT INTO country (name, code) values ('Nauru', 'NRU');
INSERT INTO country (name, code) values ('Nepal', 'NPL');
INSERT INTO country (name, code) values ('Netherlands (the)', 'NLD');
INSERT INTO country (name, code) values ('New Caledonia', 'NCL');
INSERT INTO country (name, code) values ('New Zealand', 'NZL');
INSERT INTO country (name, code) values ('Nicaragua', 'NIC');
INSERT INTO country (name, code) values ('Niger (the)', 'NER');
INSERT INTO country (name, code) values ('Nigeria', 'NGA');
INSERT INTO country (name, code) values ('Niue', 'NIU');
INSERT INTO country (name, code) values ('Norfolk Island', 'NFK');
INSERT INTO country (name, code) values ('Northern Mariana Islands (the)', 'MNP');
INSERT INTO country (name, code) values ('Norway', 'NOR');
INSERT INTO country (name, code) values ('Oman', 'OMN');
INSERT INTO country (name, code) values ('Pakistan', 'PAK');
INSERT INTO country (name, code) values ('Palau', 'PLW');
INSERT INTO country (name, code) values ('Palestine, State of', 'PSE');
INSERT INTO country (name, code) values ('Panama', 'PAN');
INSERT INTO country (name, code) values ('Papua New Guinea', 'PNG');
INSERT INTO country (name, code) values ('Paraguay', 'PRY');
INSERT INTO country (name, code) values ('Peru', 'PER');
INSERT INTO country (name, code) values ('Philippines (the)', 'PHL');
INSERT INTO country (name, code) values ('Pitcairn', 'PCN');
INSERT INTO country (name, code) values ('Poland', 'POL');
INSERT INTO country (name, code) values ('Portugal', 'PRT');
INSERT INTO country (name, code) values ('Puerto Rico', 'PRI');
INSERT INTO country (name, code) values ('Qatar', 'QAT');
INSERT INTO country (name, code) values ('Republic of North Macedonia', 'MKD');
INSERT INTO country (name, code) values ('Romania', 'ROU');
INSERT INTO country (name, code) values ('Russian Federation (the)', 'RUS');
INSERT INTO country (name, code) values ('Rwanda', 'RWA');
INSERT INTO country (name, code) values ('Réunion', 'REU');
INSERT INTO country (name, code) values ('Saint Barthélemy', 'BLM');
INSERT INTO country (name, code) values ('Saint Helena, Ascension and Tristan da Cunha', 'SHN');
INSERT INTO country (name, code) values ('Saint Kitts and Nevis', 'KNA');
INSERT INTO country (name, code) values ('Saint Lucia', 'LCA');
INSERT INTO country (name, code) values ('Saint Martin (French part)', 'MAF');
INSERT INTO country (name, code) values ('Saint Pierre and Miquelon', 'SPM');
INSERT INTO country (name, code) values ('Saint Vincent and the Grenadines', 'VCT');
INSERT INTO country (name, code) values ('Samoa', 'WSM');
INSERT INTO country (name, code) values ('San Marino', 'SMR');
INSERT INTO country (name, code) values ('Sao Tome and Principe', 'STP');
INSERT INTO country (name, code) values ('Saudi Arabia', 'SAU');
INSERT INTO country (name, code) values ('Senegal', 'SEN');
INSERT INTO country (name, code) values ('Serbia', 'SRB');
INSERT INTO country (name, code) values ('Seychelles', 'SYC');
INSERT INTO country (name, code) values ('Sierra Leone', 'SLE');
INSERT INTO country (name, code) values ('Singapore', 'SGP');
INSERT INTO country (name, code) values ('Sint Maarten (Dutch part)', 'SXM');
INSERT INTO country (name, code) values ('Slovakia', 'SVK');
INSERT INTO country (name, code) values ('Slovenia', 'SVN');
INSERT INTO country (name, code) values ('Solomon Islands', 'SLB');
INSERT INTO country (name, code) values ('Somalia', 'SOM');
INSERT INTO country (name, code) values ('South Africa', 'ZAF');
INSERT INTO country (name, code) values ('South Georgia and the South Sandwich Islands', 'SGS');
INSERT INTO country (name, code) values ('South Sudan', 'SSD');
INSERT INTO country (name, code) values ('Spain', 'ESP');
INSERT INTO country (name, code) values ('Sri Lanka', 'LKA');
INSERT INTO country (name, code) values ('Sudan (the)', 'SDN');
INSERT INTO country (name, code) values ('Suriname', 'SUR');
INSERT INTO country (name, code) values ('Svalbard and Jan Mayen', 'SJM');
INSERT INTO country (name, code) values ('Sweden', 'SWE');
INSERT INTO country (name, code) values ('Switzerland', 'CHE');
INSERT INTO country (name, code) values ('Syrian Arab Republic', 'SYR');
INSERT INTO country (name, code) values ('Taiwan (Province of China)', 'TWN');
INSERT INTO country (name, code) values ('Tajikistan', 'TJK');
INSERT INTO country (name, code) values ('Tanzania, United Republic of', 'TZA');
INSERT INTO country (name, code) values ('Thailand', 'THA');
INSERT INTO country (name, code) values ('Timor-Leste', 'TLS');
INSERT INTO country (name, code) values ('Togo', 'TGO');
INSERT INTO country (name, code) values ('Tokelau', 'TKL');
INSERT INTO country (name, code) values ('Tonga', 'TON');
INSERT INTO country (name, code) values ('Trinidad and Tobago', 'TTO');
INSERT INTO country (name, code) values ('Tunisia', 'TUN');
INSERT INTO country (name, code) values ('Turkey', 'TUR');
INSERT INTO country (name, code) values ('Turkmenistan', 'TKM');
INSERT INTO country (name, code) values ('Turks and Caicos Islands (the)', 'TCA');
INSERT INTO country (name, code) values ('Tuvalu', 'TUV');
INSERT INTO country (name, code) values ('Uganda', 'UGA');
INSERT INTO country (name, code) values ('Ukraine', 'UKR');
INSERT INTO country (name, code) values ('United Arab Emirates (the)', 'ARE');
INSERT INTO country (name, code) values ('United Kingdom of Great Britain and Northern Ireland (the)', 'GBR');
INSERT INTO country (name, code) values ('United States Minor Outlying Islands (the)', 'UMI');
INSERT INTO country (name, code) values ('United States of America (the)', 'USA');
INSERT INTO country (name, code) values ('Uruguay', 'URY');
INSERT INTO country (name, code) values ('Uzbekistan', 'UZB');
INSERT INTO country (name, code) values ('Vanuatu', 'VUT');
INSERT INTO country (name, code) values ('Venezuela (Bolivarian Republic of)', 'VEN');
INSERT INTO country (name, code) values ('Viet Nam', 'VNM');
INSERT INTO country (name, code) values ('Virgin Islands (British)', 'VGB');
INSERT INTO country (name, code) values ('Virgin Islands (U.S.)', 'VIR');
INSERT INTO country (name, code) values ('Wallis and Futuna', 'WLF');
INSERT INTO country (name, code) values ('Western Sahara', 'ESH');
INSERT INTO country (name, code) values ('Yemen', 'YEM');
INSERT INTO country (name, code) values ('Zambia', 'ZMB');
INSERT INTO country (name, code) values ('Zimbabwe', 'ZWE');
INSERT INTO country (name, code) values ('Åland Islands', 'ALA');