spring:
  h2:
    console:
      enabled: true
  liquibase:
    changeLog: "classpath:db\\changelog\\db.changelog-master.json"
  datasource:
    url: jdbc:h2:mem:srinitrial
    username: user
    password: password
  mvc:
    log-request-details: true
#trace: true
debug: true
server:
  servlet:
    session:
      cookie:
        http-only: false